echo "Running VTCD and evaluating concepts for VOS on DAVIS16"
echo "VTCD: Running VideoMAE PRE on D16 for VOS"
python run_vcd.py --exp_name VideoMAE_Pretrained_D16_train --attn_head 0 1 2 3 4 5 6 7 8 9 10 11  --max_num_videos 30 --model vidmae_ssv2_pre --dataset davis16 --cluster_layer 0 1 2 3 4 5 6 7 8 9 10 11 --cluster_subject keys --inter_cluster_method cnmf_elbow --intra_cluster_method slic --inter_max_cluster 15 --slic_compactness 0.1  --n_segments 12 --spatial_resize_factor 0.5 --inter_elbow_threshold 0.95 --pool_non_zero_features --force_reload_videos --process_full_video --preload_vcd --Eval_D16_VOS
#
echo "VTCD: Running VideoMAE FT on D16 for VOS"
python run_vcd.py --exp_name VideoMAE_D16_train --attn_head 0 1 2 3 4 5 6 7 8 9 10 11 --max_num_videos 30 --model vidmae_ssv2_ft --dataset davis16 --cluster_layer 0 1 2 3 4 5 6 7 8 9 10 11 --cluster_subject keys --inter_cluster_method cnmf_elbow --intra_cluster_method slic --inter_max_cluster 15 --slic_compactness 0.1  --n_segments 12 --spatial_resize_factor 0.5 --inter_elbow_threshold 0.95 --pool_non_zero_features --force_reload_videos --process_full_video --preload_vcd --Eval_D16_VOS

echo "VTCD: Running Intern on D16 for VOS"
python run_vcd.py --exp_name Intern_D16_train --attn_head 0 1 2 3 4 5 6 7 8 9 10 11 --max_num_videos 30 --model intern --dataset davis16 --cluster_layer 0 1 2 3 4 5 6 7 8 9 10 11 --cluster_subject keys --inter_cluster_method cnmf_elbow --intra_cluster_method slic --inter_max_cluster 15 --slic_compactness 0.15  --n_segments 10 --spatial_resize_factor 0.5 --inter_elbow_threshold 0.95 --pool_non_zero_features --force_reload_videos --process_full_video --preload_vcd --Eval_D16_VOS




echo "########## VOS ##########"
echo "VTCD: Running VideoMAE PRE on D16 for VOS"
python run_vcd.py --exp_name VideoMAE_Pretrained_D16_val --attn_head 0 1 2 3 4 5 6 7 8 9 10 11  --max_num_videos 30 --model vidmae_ssv2_pre --dataset davis16_val --cluster_layer 0 1 2 3 4 5 6 7 8 9 10 11 --cluster_subject keys --inter_cluster_method cnmf_elbow --intra_cluster_method slic --inter_max_cluster 15 --slic_compactness 0.1  --n_segments 12 --spatial_resize_factor 0.5 --inter_elbow_threshold 0.95 --pool_non_zero_features --force_reload_videos --first_frame_query --train_head_search --process_full_video
python run_vcd.py --exp_name VideoMAE_Pretrained_D16_val --attn_head 0 1 2 3 4 5 6 7 8 9 10 11  --max_num_videos 30 --model vidmae_ssv2_pre --dataset davis16_val --cluster_layer 0 1 2 3 4 5 6 7 8 9 10 11 --cluster_subject keys --inter_cluster_method cnmf_elbow --intra_cluster_method slic --inter_max_cluster 15 --slic_compactness 0.1  --n_segments 12 --spatial_resize_factor 0.5 --inter_elbow_threshold 0.95 --pool_non_zero_features --force_reload_videos --preload_vcd --first_frame_query --train_head_search --post_sam --sam_sampling_mode centroid --process_full_video --num_sam_points 2 --sample_factor 10 --use_last_centroid --use_box --Eval_D16_VOS

echo "VTCD: Running VideoMAE FT on D16 for VOS"
python run_vcd.py --exp_name VideoMAE_D16_val --attn_head 0 1 2 3 4 5 6 7 8 9 10 11  --max_num_videos 30 --model vidmae_ssv2_ft --dataset davis16_val --cluster_layer 0 1 2 3 4 5 6 7 8 9 10 11 --cluster_subject keys --inter_cluster_method cnmf_elbow --intra_cluster_method slic --inter_max_cluster 15 --slic_compactness 0.1  --n_segments 12 --spatial_resize_factor 0.5 --inter_elbow_threshold 0.95 --pool_non_zero_features --force_reload_videos --first_frame_query --process_full_video
python run_vcd.py --exp_name VideoMAE_D16_val --attn_head 0 1 2 3 4 5 6 7 8 9 10 11  --max_num_videos 30 --model vidmae_ssv2_ft --dataset davis16_val --cluster_layer 0 1 2 3 4 5 6 7 8 9 10 11 --cluster_subject keys --inter_cluster_method cnmf_elbow --intra_cluster_method slic --inter_max_cluster 15 --slic_compactness 0.1  --n_segments 12 --spatial_resize_factor 0.5 --inter_elbow_threshold 0.95 --pool_non_zero_features --force_reload_videos --preload_vcd --first_frame_query --train_head_search --post_sam --sam_sampling_mode centroid --process_full_video --num_sam_points 2 --sample_factor 10 --use_last_centroid --use_box --Eval_D16_VOS

echo "VTCD: Running Intern on D16 for VOS"
python run_vcd.py --exp_name Intern_D16_val --attn_head 0 1 2 3 4 5 6 7 8 9 10 11  --max_num_videos 30 --model intern --dataset davis16_val --cluster_layer 0 1 2 3 4 5 6 7 8 9 10 11 --cluster_subject keys --inter_cluster_method cnmf_elbow --intra_cluster_method slic --inter_max_cluster 15 --slic_compactness 0.1  --n_segments 12 --spatial_resize_factor 0.5 --inter_elbow_threshold 0.95 --pool_non_zero_features --force_reload_videos --first_frame_query --process_full_video
python run_vcd.py --exp_name Intern_D16_val --attn_head 0 1 2 3 4 5 6 7 8 9 10 11  --max_num_videos 30 --model intern --dataset davis16_val --cluster_layer 0 1 2 3 4 5 6 7 8 9 10 11 --cluster_subject keys --inter_cluster_method cnmf_elbow --intra_cluster_method slic --inter_max_cluster 15 --slic_compactness 0.1  --n_segments 12 --spatial_resize_factor 0.5 --inter_elbow_threshold 0.95 --pool_non_zero_features --force_reload_videos --preload_vcd --first_frame_query --train_head_search --post_sam --sam_sampling_mode centroid --process_full_video --num_sam_points 2 --sample_factor 10 --use_last_centroid --use_box --Eval_D16_VOS
